//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllplanBimplusDemo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AllplanBimplusDemo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;levelofdetail&quot;: 0,
        ///    &quot;identifier&quot;: &quot;bolt_5074991643486136591&quot;,
        ///    &quot;meshes&quot;: [
        ///        {
        ///            &quot;color&quot;: 4284510336,
        ///            &quot;vertices&quot;: [
        ///                18.331,
        ///                0,
        ///                11.957,
        ///                9.165,
        ///                15.875,
        ///                11.957,
        ///                -9.165,
        ///                15.875,
        ///                11.957,
        ///                -18.331,
        ///                0,
        ///                11.957,
        ///                -9.165,
        ///                -15.875,
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        public static string bolt_5074991643486136591 {
            get {
                return ResourceManager.GetString("bolt_5074991643486136591", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Axis xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;HorizontalAlignments&gt;
        ///    &lt;HorizontalAlignment&gt;
        ///      &lt;Elements&gt;
        ///        &lt;HorizontalElement xsi:type=&quot;StraightHorizontalElement&quot;&gt;
        ///          &lt;Station&gt;91644.7291&lt;/Station&gt;
        ///          &lt;Length&gt;100000&lt;/Length&gt;
        ///          &lt;StartX&gt;579911855.5371&lt;/StartX&gt;
        ///          &lt;StartY&gt;246492852.9281&lt;/StartY&gt;
        ///          &lt;Bearing&gt;0.5975665514&lt;/Bearing&gt;
        ///        &lt;/HorizontalElement&gt;
        ///        &lt;H [rest of string was truncated]&quot;;.
        /// </summary>
        public static string cadicsData {
            get {
                return ResourceManager.GetString("cadicsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;Elements&quot;: [{
        ///			&quot;elementType&quot;: &quot;Line&quot;,
        ///			&quot;Station&quot;: 0,
        ///			&quot;Length&quot;: 43296.95011294631,
        ///			&quot;StartX&quot;: 4056251733.0988838,
        ///			&quot;StartY&quot;: 178408590.91706986,
        ///			&quot;Bearing&quot;: 1.5342825747807823
        ///		},
        ///		{
        ///			&quot;elementType&quot;: &quot;Arc&quot;,
        ///			&quot;R&quot;: 91440.00000000002,
        ///			&quot;EndX&quot;: 4056261216.8715674,
        ///			&quot;EndY&quot;: 178485844.5745946,
        ///			&quot;Station&quot;: 43296.95011294631,
        ///			&quot;Length&quot;: 35107.63320416572,
        ///			&quot;StartX&quot;: 4056253313.681709,
        ///			&quot;StartY&quot;: 178451859.00747163,
        ///			&quot;Bearing&quot;: 1.5342825747676548
        ///		},
        ///		{
        ///			&quot;e [rest of string was truncated]&quot;;.
        /// </summary>
        public static string horizontalAlignment {
            get {
                return ResourceManager.GetString("horizontalAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;Elements&quot;: [{
        ///		&quot;elementType&quot;: &quot;Line&quot;,
        ///		&quot;Station&quot;: 0,
        ///		&quot;Length&quot;: 137200,
        ///		&quot;StartX&quot;: 4056251733.0988836,
        ///		&quot;StartY&quot;: 178408590.91706985,
        ///		&quot;Bearing&quot;: 0.93
        ///	}]
        ///}.
        /// </summary>
        public static string horizontalAlignmentRev2 {
            get {
                return ResourceManager.GetString("horizontalAlignmentRev2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static string IOM_SteelFrame {
            get {
                return ResourceManager.GetString("IOM_SteelFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;Elements&quot;: [{
        ///			&quot;type&quot;: &quot;Line&quot;,
        ///			&quot;StartStation&quot;: 1.1641532182693482e-7,
        ///			&quot;StartElevation&quot;: 238556.30171904205,
        ///			&quot;Slope&quot;: 0.015413437368460565,
        ///			&quot;ProjectedLength&quot;: 43296.95011282989
        ///		},
        ///		{
        ///			&quot;type&quot;: &quot;Line&quot;,
        ///			&quot;StartStation&quot;: 43296.9501129463,
        ///			&quot;StartElevation&quot;: 239223.6565478515,
        ///			&quot;Slope&quot;: 0.020000000000036368,
        ///			&quot;ProjectedLength&quot;: 304.8000000001281
        ///		},
        ///		{
        ///			&quot;type&quot;: &quot;Parabola&quot;,
        ///			&quot;R&quot;: 497839.99999997045,
        ///			&quot;EndStation&quot;: 73472.15011294642,
        ///			&quot;EndElevation&quot;: 24072 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string verticalAlignment {
            get {
                return ResourceManager.GetString("verticalAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;Elements&quot;: [{
        ///			&quot;type&quot;: &quot;Line&quot;,
        ///			&quot;StartStation&quot;: 1.1641532182693481E-07,
        ///			&quot;StartElevation&quot;: 238556.30171904204,
        ///			&quot;Slope&quot;: 0.015413437368460564,
        ///			&quot;ProjectedLength&quot;: 43296.950112829887
        ///		},
        ///		{
        ///			&quot;type&quot;: &quot;Line&quot;,
        ///			&quot;StartStation&quot;: 43296.9501129463,
        ///			&quot;StartElevation&quot;: 239223.65654785151,
        ///			&quot;Slope&quot;: 0.020000000000036367,
        ///			&quot;ProjectedLength&quot;: 304.80000000012808
        ///		},
        ///		{
        ///			&quot;type&quot;: &quot;Parabola&quot;,
        ///			&quot;R&quot;: 497839.99999997043,
        ///			&quot;EndStation&quot;: 73472.150112946416,
        ///			&quot;EndElevation&quot;:  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string verticalAlignmentRev2 {
            get {
                return ResourceManager.GetString("verticalAlignmentRev2", resourceCulture);
            }
        }
    }
}
